services:
  users-api:
    image: users_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5098:5098
    depends_on:
      db:
        condition: service_healthy

  products-api:
    image: products_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5245:5245
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: InnoShopDB
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d InnoShopDB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
